# Generated by Django 3.2.5 on 2021-10-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CANDIDATE', 'CANDIDATE'), ('ASSESSOR', 'ASSESSOR'), ('ADMIN', 'ADMIN')], default='ADMIN', max_length=50),
        ),
    ]
