# Generated by Django 3.2.7 on 2021-10-06 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.company'),
        ),
        migrations.AddField(
            model_name='interview',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='job.assessor'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='job.job'),
        ),
        migrations.AddField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='job.candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='users.company'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobs',
            field=models.ManyToManyField(related_name='candidates', to='job.Job'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='jobs',
            field=models.ManyToManyField(related_name='assessors', to='job.Job'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessors', to=settings.AUTH_USER_MODEL),
        ),
    ]
