# Generated by Django 3.2.5 on 2021-10-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20211013_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cv',
        ),
    ]
